#!/bin/sh

PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

mmhextodec() {
    local major minor
    set -- ${1##*[!0-9a-fA-F]*}

    major=$((0x$1 >> 8))
    minor=$((0x$1 & 255))

    echo "${major}:${minor}"
}

mmblock_prop() {
    udevadm info -q property /sys/dev/block/"$1" | grep "^$2="
}

has_crypt_parent() {
    local mm DM_NAME DEVNAME

    mm="$1"

    while :; do
        DM_NAME=''
        eval "$(mmblock_prop "${mm}" DM_NAME)"

        if [ -z "${DM_NAME}" ]; then
            eval "$(mmblock_prop "${mm}" DEVNAME)"
            echo "WARNING: Cannot resolve DM parent of ${mm}[${DEVNAME}]" >&2
            return 1
        fi

        eval $(dmsetup table "${DM_NAME}" | awk '
            $3 == "crypt" { print $3, $7; }
            $3 == "linear" { print $3, $4; }' | { read -r dmtype mm;
            echo "dmtype=${dmtype} mm=${mm}"
        })
        
        [ "$dmtype" == "crypt" ] && return 0
    done
}

if ! has_crypt_parent $(mmhextodec "$(stat -c %D /boot)"); then
    echo "ERROR: /boot doesn't seem to reside on a dm_crypt device!" >&2
    exit 1
fi


mkdir -p "${DESTDIR}/scripts"

echo '#!/bin/sh' > "${DESTDIR}/scripts/localcrypt"
dmsetup table --showkeys | \
	awk '$4 == "crypt" {
		name=$1;
		sub(/:$/, "", name);
		$1 = "";
		sub(/^ +/, "", $0);
		print "dmsetup create " name " --table \"" $0 "\"";
	}' >> "${DESTDIR}/scripts/localcrypt"
chmod 755 "${DESTDIR}/scripts/localcrypt"

for mod in dm_mod dm_crypt aes-x86_64 aesni-intel; do
	manual_add_modules "$mod"
done

copy_exec /sbin/dmsetup
